TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.01
  acc_lim_y
  max_vel_theta: 1.667
  min_in_place_vel_theta: 0.01

  path_distance_bias: 0.15

  acc_lim_theta: 1.5
  acc_lim_x: 1
  acc_lim_y: 1


  holonomic_robot: true
  sim_time: 2.0 # before 1.0
