#transform_tolerance: 0.2
map_type: costmap

footprint: [[-0.71629, 0.290], [-0.71629, -0.290], [0.71629, -0.290], [0.71629, 0.290]]
footprint_padding: 0.1

#static_layer:
#  enabled: true
#  map_topic: "/map"

#obstacle_layer:
# enabled: true
# obstacle_range: 10.0
# raytrace_range: 4.0
# min_obstacle_height: 0.0
# max_obstacle_height: 2.0
# inflation_radius: 0.6
# track_unknown_space: true
# combination_method: 1

#observation_sources: laser_scan_sensor
#laser_scan_sensor: {data_type: LaserScan, topic: merged_scan, marking: true, clearing: true}

#inflation_layer:
#  enabled: true
#  cost_scaling_factor: 10.0 # exponential rate at which the obstacle cost drops off (default: 10)
#  inflation_radius: 0.6  # max. distance from an obstacle at which costs are incurred for planning paths.
