global_costmap:
  update_frequency: 1.0
  static_map: true
  rolling_window: false
  global_frame: map
  robot_base_frame: base_lnk
  publish_frequency: 0.5
  resolution: 0.04
  transform_tolerance: 1

  static_layer:
    map_topic: "map"
    subscribe_to_updates: true
    lethal_cost_threshold: 60

  inflater_layer:
    inflation_radius: 0.6
    cost_scaling_factor: 0.5

  obstacle_layer:
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {sensor_frame: laser_lnk, data_type: LaserScan, topic: merged_scan, marking: true, clearing: true}
    max_obstacle_height: 2
    obstacle_range: 6
    raytrace_range: 7

  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
