local_costmap:
  global_frame: odom
  robot_base_frame: base_lnk
  update_frequency: 1.0
  publish_frequency: 1.0
  static_map: false
  rolling_window: true
  width: 8.0
  height: 8.0
  resolution: 0.04
  transform_tolerance: 1

  inflater_layer:
    inflation_radius: 0.5
    cost_scaling_factor: 0.5

  obstacle_layer:
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {sensor_frame: laser_lnk, data_type: LaserScan, topic: merged_scan, marking: true, clearing: true}
    max_obstacle_height: 2
    obstacle_range: 6
    raytrace_range: 7

  plugins:
   - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
   - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}

