shutdown_costmaps: false

controller_frequency: 15.0 #before 15.0
controller_patience: 5.0

planner_frequency: 1.0
planner_patience: 5.0
max_planning_retries: -1

oscillation_timeout: 0.0
oscillation_distance: 0.1 #before 0.5

conservative_reset_dist: 0.8 #distance from an obstacle at which it will unstuck itself

cost_factor: 0.55
neutral_cost: 66
lethal_cost: 253

