# Minimum sensor range (m).
range_min: 0.25
# Maximum sensor range (m).
range_max: 10.0
# Height of used part of depth img (px).
scan_height: 512
scan_width: 512
# Row step in depth image processing (px).
depth_img_row_step: 1
# If continously camera data update.
cam_model_update: false

# Height of sensor optical center mount (m).
sensor_mount_height: 0.2
# Remove ground from scan.
ground_remove_en: true
# Ground margin (m).
ground_margin: 0.05
# Sensor tilt angle compensation.
tilt_compensation_en: false
# Sensor tilt angle compensation.
sensor_tilt_angle: 5.0
